# Build settings
gems:
  - jekyll-paginate

# Site settings
title: "L'Escèptic"
name: "L'Escèptic"
description: > # this means to ignore newlines until "email:"
   La teva revista científica digital en català

email: contact@gerard.space
#blog logo
logo: "/assets/images/Logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/Portada.jpg"

paginate: 5

# used to display twitter cards
twitter_handle: '@casassaez'

#fill in disqus shortname to use disqus
disqus: Casassaez

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/casassaez
    desc: Segueix-nos al Twitter
    share_url: http://twitter.com/share
    share_title: "?text="
    share_link: "&amp;url="

  - icon: github
    url: https://github.com/futuracat
    desc: Trobans al GitHub
    share_url: 
    share_title: 
    share_link: 

  - icon: facebook
    url: https://facebook.com/???
    desc: Connecta al Facebook
    share_url: https://www.facebook.com/sharer/sharer.php
    share_title: "?text="
    share_link: "&u="

  # - icon:	github
  #   url:	https://github.com/casassg
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
